# Generated by Django 5.2.1 on 2025-05-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="bio",
        ),
        migrations.AddField(
            model_name="customuser",
            name="password",
            field=models.CharField(default="Updated User model", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="username",
            field=models.CharField(default="username", max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
